Caarta/Controllers/DecksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Caarta.Data;
using Caarta.Data.Entities;
using Caarta.Services.Abstractions;
using Caarta.Services.DTOs;
using Caarta.Services.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Hosting;
using Caarta.Services;

namespace Caarta.Controllers
{
    public class DecksController : Controller
    {
        private readonly IDeckService _deckService;
        private readonly ICategoryService _categoryService;
        private readonly ILanguageService _languageService;
        private readonly UserManager<AppUser> _userManager;
        private readonly IWebHostEnvironment _environment;

        public DecksController(IDeckService deckService, ICategoryService categoryService, ILanguageService languageService, UserManager<AppUser> userManager, IWebHostEnvironment environment)
        {
            _deckService = deckService;
            _categoryService = categoryService;
            _languageService = languageService;
            _userManager = userManager;
            _environment = environment;
        }

        // GET: Decks
        public async Task<IActionResult> Index()
        {
            return View(await _deckService.GetAllAsync());
        }

        // GET: Decks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deck = await _deckService.GetByIdAsync(id.Value);
            if (deck == null)
            {
                return NotFound();
            }

            return View(deck);
        }

        // GET: Decks/Create
        [Authorize]
        public async Task<IActionResult> Create()
        {

            var userId = (await _userManager.GetUserAsync(User)).Id;
            if (userId == null)
            {
                return NotFound();
            }
            var deckDto = new CreateDeckDTO()
            {
                CreatorId = userId,
                Categories = (await _categoryService.GetAllAsync())
                    .Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name })
                    .ToList(),
                Languages = (await _languageService.GetAllAsync())
                    .Select(l => new SelectListItem { Value = l.Id.ToString(), Text = l.Name })
                    .ToList(),
                CreateCards = new List<CreateCardDTO> { new CreateCardDTO() }
            };

            return View(deckDto);
        }

        // POST: Decks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateDeckDTO model)
        {
            model.TimeOfCreation = DateTime.Now;
            if (ModelState.IsValid)
            {
                foreach (var card in model.CreateCards)
                {
                    if (card.FrontPicture != null && card.FrontPicture.Length > 0)
                    {
                        var newFileName = await FileUpload.UploadAsync(card.FrontPicture, _environment.WebRootPath);
                        card.FrontPictureUrl = newFileName;
                    }
                    if (card.BackPicture != null && card.BackPicture.Length > 0)
                    {
                        var newFileName = await FileUpload.UploadAsync(card.BackPicture, _environment.WebRootPath);
                        card.BackPictureUrl = newFileName;
                    }

                }
                var deck = new DeckDTO()
                {
                    Name = model.Name,
                    CreatorId = model.CreatorId,
                    CategoryId = model.CategoryId,
                    LanguageId = model.LanguageId,
                    TimeOfCreation = model.TimeOfCreation,
                    Cards = model.CreateCards.Select(c => new CardDTO
                    {
                        FrontText = c.FrontText,
                        BackText = c.BackText,
                        FrontPictureUrl = c.FrontPictureUrl,
                        BackPictureUrl = c.BackPictureUrl,
                        CardType = c.CardType
                    }).ToList()
                };
                await _deckService.CreateAsync(deck);
       
                return RedirectToAction(nameof(Index));
            }
            Console.WriteLine("-------------------------------------------------");
            foreach (var modelError in ModelState.Values.SelectMany(v => v.Errors))
            {
                Console.WriteLine(modelError.ErrorMessage);
            }
            Console.WriteLine("-------------------------------------------------");
            return View(model);
        }

        // GET: Decks/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deck = await _deckService.GetByIdAsync(id.Value);
            if (deck == null)
            {
                return NotFound();
            }

            if (!User.IsInRole("Admin") && deck.CreatorId != (await _userManager.GetUserAsync(User)).Id)
            {
                return NotFound();
            }

            var createDeck = new CreateDeckDTO()
            {
                Name = deck.Name,
                CreatorId = deck.CreatorId,
                CategoryId = deck.CategoryId,
                LanguageId = deck.LanguageId,
                Categories = (await _categoryService.GetAllAsync())
                    .Select(c => new SelectListItem { Value = c.Id.ToString(), Text = c.Name })
                    .ToList(),
                Languages = (await _languageService.GetAllAsync())
                    .Select(l => new SelectListItem { Value = l.Id.ToString(), Text = l.Name })
                    .ToList(),
                IsPublic = deck.IsPublic,
                TimeOfCreation = deck.TimeOfCreation
            };

            return View(createDeck);
        }

        // POST: Decks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CreateDeckDTO deck)
        {
            if (id != deck.Id)
            {
                return NotFound();
            }
            if (!User.IsInRole("Admin") && deck.CreatorId != (await _userManager.GetUserAsync(User)).Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    await _deckService.UpdateAsync(deck);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await DeckExistsAsync(deck.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(deck);
        }

        // GET: Decks/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deck = await _deckService.GetByIdAsync(id.Value);
            if (deck == null)
            {
                return NotFound();
            }
            if (!User.IsInRole("Admin") && deck.CreatorId != (await _userManager.GetUserAsync(User)).Id)
            {
                return NotFound();
            }

            return View(deck);
        }

        // POST: Decks/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!User.IsInRole("Admin") && (await _deckService.GetByIdAsync(id)).CreatorId != (await _userManager.GetUserAsync(User)).Id)
            {
                return NotFound();
            }
            await _deckService.DeleteByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> DeckExistsAsync(int id)
        {
            var deck = await _deckService.GetByIdAsync(id);
            return deck != null;
        }

        [Authorize]
        public async Task<IActionResult> Save(int id)
        {
            var deck = await _deckService.GetByIdAsync(id);
            if (deck == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound();
            }
            if (user.Saved.Any(item => item.DeckId == id))
            {
                return NotFound();
            }
            var userSaveDeck = new UserSaveDeckDTO()
            {
                DeckId = deck.Id,
                AppUserId = user.Id,
                TimeOfSaving = DateTime.Now
            };
            await _deckService.AddUserSaveDeckAsync(userSaveDeck);
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<IActionResult> Unsave(int id)
        {
            var deck = await _deckService.GetByIdAsync(id);
            if (deck == null)
            {

Caarta/Controllers/LanguagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Caarta.Data;
using Caarta.Data.Entities;
using Caarta.Services.Abstractions;
using Caarta.Services.DTOs;
using Microsoft.AspNetCore.Authorization;

namespace Caarta.Controllers
{
    public class LanguagesController : Controller
    {
        private readonly ILanguageService _languageService;

        public LanguagesController(ILanguageService languageService)
        {
            _languageService = languageService;
        }

        // GET: Languages
        public async Task<IActionResult> Index()
        {
            return View(await _languageService.GetAllAsync());
        }

        // GET: Languages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var language = await _languageService.GetByIdAsync(id.Value);
            if (language == null)
            {
                return NotFound();
            }

            return View(language);
        }

        // GET: Languages/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Languages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id")] LanguageDTO language)
        {
            if (ModelState.IsValid)
            {
                await _languageService.CreateAsync(language);
                return RedirectToAction(nameof(Index));
            }
            return View(language);
        }

        // GET: Languages/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var language = await _languageService.GetByIdAsync(id.Value);
            if (language == null)
            {
                return NotFound();
            }
            return View(language);
        }

        // POST: Languages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id")] LanguageDTO language)
        {
            if (id != language.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _languageService.UpdateAsync(language);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await LanguageExistsAsync(language.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(language);
        }

        // GET: Languages/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var language = await _languageService.GetByIdAsync(id.Value);
            if (language == null)
            {
                return NotFound();
            }

            return View(language);
        }

        // POST: Languages/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _languageService.DeleteByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> LanguageExistsAsync(int id)
        {
            var language = await _languageService.GetByIdAsync(id);
            return language != null;
        }
    }
}

Caarta/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"] - Caarta</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CatsMVC.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/png" href="~/img/Loquit.png" sizes="640x640">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3 fixed-top">
            <div class="container-fluid">
                <img id="logo" src="~/img/CaartaLogo.png" />
                <a class="navbar-name" asp-area="" asp-controller="Home" asp-action="Index">Caarta</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="midder container-fluid">
        <main role="main" class="render-body screen">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Caarta/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Caarta</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="icon" type="image/png" href="~/img/CaartaLogo.png" sizes="640x640">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img id="logo" src="~/img/CaartaLogo.png" />
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Caarta</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Decks" asp-action="Index">Decks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cardlists" asp-action="Index">Cardlists</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Languages" asp-action="Index">Languages</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Index">Users</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

@*     <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CatsMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>