Caarta/Controllers/CardlistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Caarta.Data;
using Caarta.Data.Entities;
using Caarta.Services.Abstractions;
using Caarta.Services.DTOs;
using Caarta.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Caarta.Services.Services;

namespace Caarta.Controllers
{
    public class CardlistsController : Controller
    {
        private readonly IDeckService _deckService;
        private readonly ICategoryService _categoryService;
        private readonly ILanguageService _languageService;
        private readonly ICardlistService _cardlistService;
        private readonly UserManager<AppUser> _userManager;
        private readonly IWebHostEnvironment _environment;

        public CardlistsController(IDeckService deckService, ICardlistService cardlistService, ICategoryService categoryService, ILanguageService languageService, UserManager<AppUser> userManager, IWebHostEnvironment environment)
        {
            _deckService = deckService;
            _cardlistService = cardlistService;
            _categoryService = categoryService;
            _languageService = languageService;
            _userManager = userManager;
            _environment = environment;
        }

        // GET: Cardlists
        public async Task<IActionResult> Index()
        {
            return View(await _cardlistService.GetAllAsync());
        }

        // GET: Cardlists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cardlist = await _cardlistService.GetByIdAsync(id.Value);
            if (cardlist == null)
            {
                return NotFound();
            }

            return View(cardlist);
        }

        // GET: Cardlists/Create
        [Authorize]
        public async Task<IActionResult> Create()
        {

            var userId = (await _userManager.GetUserAsync(User)).Id;
            if (userId == null)
            {
                return NotFound();
            }
            var cardlistDto = new CreateCardlistDTO()
            {
                CreatorId = userId,
                Languages = (await _languageService.GetAllAsync())
                    .Select(l => new SelectListItem { Value = l.Id.ToString(), Text = l.Name })
                    .ToList()
            };

            return View(cardlistDto);
        }

        // POST: Cardlists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCardlistDTO model)
        {
            model.TimeOfCreation = DateTime.Now;
            if (ModelState.IsValid)
            {
                var cardlist = new CardlistDTO()
                {
                    Name = model.Name,
                    CreatorId = model.CreatorId,
                    LanguageId = model.LanguageId,
                    TimeOfCreation = model.TimeOfCreation
                };
                await _cardlistService.CreateAsync(cardlist);

                return RedirectToAction(nameof(Index));
            }
            Console.WriteLine("-------------------------------------------------");
            foreach (var modelError in ModelState.Values.SelectMany(v => v.Errors))
            {
                Console.WriteLine(modelError.ErrorMessage);
            }
            Console.WriteLine("-------------------------------------------------");
            return View(model);
        }

        // GET: Cardlists/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cardlist = await _cardlistService.GetByIdAsync(id.Value);
            if (cardlist == null)
            {
                return NotFound();
            }

            if (!User.IsInRole("Admin") && cardlist.CreatorId != (await _userManager.GetUserAsync(User)).Id)
            {
                return NotFound();
            }

            var createCardlist = new CreateCardlistDTO()
            {
                Name = cardlist.Name,
                CreatorId = cardlist.CreatorId,
                LanguageId = cardlist.LanguageId,
                Languages = (await _languageService.GetAllAsync())
                    .Select(l => new SelectListItem { Value = l.Id.ToString(), Text = l.Name })
                    .ToList(),
                IsPublic = cardlist.IsPublic,
                TimeOfCreation = cardlist.TimeOfCreation
            };

            return View(createCardlist);
        }

        // POST: Cardlists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CreateCardlistDTO cardlist)
        {
            if (id != cardlist.Id)
            {
                return NotFound();
            }
            if (!User.IsInRole("Admin") && cardlist.CreatorId != (await _userManager.GetUserAsync(User)).Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    await _cardlistService.UpdateAsync(cardlist);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await CardlistExistsAsync(cardlist.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cardlist);
        }

        // GET: Cardlists/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cardlist = await _cardlistService.GetByIdAsync(id.Value);
            if (cardlist == null)
            {
                return NotFound();
            }
            if (!User.IsInRole("Admin") && cardlist.CreatorId != (await _userManager.GetUserAsync(User)).Id)
            {
                return NotFound();
            }

            return View(cardlist);
        }

        // POST: Cardlists/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!User.IsInRole("Admin") && (await _cardlistService.GetByIdAsync(id)).CreatorId != (await _userManager.GetUserAsync(User)).Id)
            {
                return NotFound();
            }
            await _cardlistService.DeleteByIdAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> CardlistExistsAsync(int id)
        {
            var cardlist = await _cardlistService.GetByIdAsync(id);
            return cardlist != null;
        }

        public async Task<IActionResult> CheckYourself(int id)
        {
            var cardlist = await _cardlistService.GetByIdAsync(id);
            if (cardlist == null)
            {
                return NotFound();
            }
            var simpleCardlist = new CardlistSimpleDTO()
            {
                Id = cardlist.Id,
                Name = cardlist.Name,
                LanguageId = cardlist.LanguageId,
                TimeOfCreation = cardlist.TimeOfCreation,
                SimpleCards = cardlist.Decks
                    .Where(d => d.Deck != null)
                    .SelectMany(d => d.Deck.Cards)
                    .OrderBy(c => Guid.NewGuid())
                    .Select(c => new CardSimpleDTO
                    {
                        FrontText = c.FrontText,
                        BackText = c.BackText,
                        FrontPictureUrl = c.FrontPictureUrl,
                        BackPictureUrl = c.BackPictureUrl
                    }).ToList()
            };

            return View(simpleCardlist);
        }

        public async Task<IActionResult> Test(int id)
        {
            var cardlist = await _cardlistService.GetByIdAsync(id);
            if (cardlist == null)
            {
                return NotFound();
            }
            var simpleCardlist = new CardlistSimpleDTO()
            {
                Id = cardlist.Id,
                Name = cardlist.Name,
                LanguageId = cardlist.LanguageId,
                TimeOfCreation = cardlist.TimeOfCreation,
                SimpleCards = cardlist.Decks
                    .Where(d => d.Deck != null)
                    .SelectMany(d => d.Deck.Cards)
                    .OrderBy(c => Guid.NewGuid())
                    .Select(c => new CardSimpleDTO
                    {
                        FrontText = c.FrontText,
                        BackText = c.BackText,
                        FrontPictureUrl = c.FrontPictureUrl,
                        BackPictureUrl = c.BackPictureUrl
                    }).ToList()
            };

            return View(simpleCardlist);
        }
        public async Task<IActionResult> TestReversed(int id)
        {
            var cardlist = await _cardlistService.GetByIdAsync(id);
            if (cardlist == null)
            {
                return NotFound();
            }

Caarta/Views/Cardlists/CheckYourself.cshtml
@model CardlistSimpleDTO

@{
    ViewData["Title"] = "Check Yourself";
    var cards = Model.SimpleCards;
}

<div id="cards-container" class="d-flex justify-content-center align-items-center vh-100 flex-column">
    <h4 id="cards-counter">
        1/@cards.Count
    </h4>
    <div class="d-flex justify-content-center align-items-center">
        <button class="know-button" onclick="PressKnow(false)">
            <img src="~/img/NO.png" />
        </button>
        <div class="card-container" onclick="flipCard(this)">
            <div class="card-inner">
                <div class="card-front d-flex flex-column">
                    @if (!string.IsNullOrEmpty(cards[0].FrontPictureUrl))
                    {
                        <img src="~/uploads/@cards[0].FrontPictureUrl" class="card-img" loading="lazy">
                    }
                    <div class="card-text-box">
                        <p class="card-text">@cards[0].FrontText</p>
                    </div>
                </div>

                <div class="card-back d-flex flex-column">
                    @if (!string.IsNullOrEmpty(cards[0].BackPictureUrl))
                    {
                        <img src="~/uploads/@cards[0].BackPictureUrl" class="card-img" loading="lazy">
                    }
                    <div class="card-text-box">
                        <p class="card-text">@cards[0].BackText</p>
                    </div>
                </div>
            </div>
        </div>
        <button class="know-button" onclick="PressKnow(true)">
            <img src="~/img/YES.png" />
        </button>
    </div>
    <div>
        <a class="btn btn-light" id="back-to-deck" asp-action="Details" asp-route-id="@Model.Id">Back to Cardlist</a>
    </div>
</div>

<script id="modelData" type="application/json">
    @Html.Raw(Json.Serialize(Model.SimpleCards))
</script>
<script src="~/js/CheckYourself.js"></script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Caarta/Views/Cardlists/Create.cshtml
@model CreateCardlistDTO

@{
    ViewData["Title"] = "Create";
}
<div class="d-flex align-items-center vh-100 flex-column" style="margin-top: 7rem">

    <h3>Create Cardlist</h3>
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-floating mb-3">

                <input asp-for="Name" class="form-control">
                <label asp-for="Name" class="form-label">Name</label>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">

                <select asp-for="LanguageId" asp-items="Model.Languages" class="form-control"></select>
                <label asp-for="LanguageId" class="form-label">Language</label>
            </div>
            <div class="form-floating mb-3">

                <select asp-for="IsPublic" class="form-control">
                    <option value="true">Public</option>
                    <option value="false">Private</option>
                </select>
                <label asp-for="IsPublic" class="form-label">Visibility</label>
            </div>
            <input type="hidden" asp-for="CreatorId" />
            <input type="hidden" asp-for="TimeOfCreation" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a class="btn btn-light" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Caarta/Views/Cardlists/Delete.cshtml
@model CardlistDTO

@{
    ViewData["Title"] = "Delete";
}
<div class="my-main">
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Cardlist</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Creator)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Creator.UserName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Language)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Language.Name)
            </dd>
            <dt class="col-sm-2">
                Visibility
            </dt>
            <dd class="col-sm-10">
                @(Model.IsPublic ? "Public" : "Private")
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TimeOfCreation)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TimeOfCreation)
            </dd>
        </dl>
        <hr />
        <form asp-action="Delete" class="d-flex justify-content-center align-items-center flex-wrap">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a class="btn btn-light" asp-action="Index">Back to List</a>
        </form>
    </div>
</div>

Caarta/Views/Cardlists/Details.cshtml
@model CardlistDTO
@inject UserManager<AppUser> _userManager
@inject SignInManager<AppUser> SignInManager

@{
    ViewData["Title"] = "Details";
    var currentUser = await _userManager.GetUserAsync(User);
    var signedIn = SignInManager.IsSignedIn(User);
}
<div class="my-main">

    <div>
        <h4>Cardlist</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Creator)
            </dt>
            <dd class="col-sm-10">
                <a asp-controller="Profile" asp-action="Details" asp-route-id="@Model.CreatorId">@Html.DisplayFor(model => model.Creator.UserName)</a>
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Language)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Language.Name)
            </dd>
            @*             <dt class="col-sm-2">
                Visibility
            </dt>
            <dd class="col-sm-10">
                @(Model.IsPublic ? "Public" : "Private")
            </dd> *@
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TimeOfCreation)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TimeOfCreation)
            </dd>
        </dl>
        <hr />
    </div>

    <div>
        <a class="btn btn-success" onclick="ChooseGamemode2(@Model.Id, @Model.Decks.Count)">Play</a>
        @if (signedIn)
        {
            @if (User.IsInRole("Admin") || currentUser.Id == Model.CreatorId)
            {
                <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
            }
        }
        <a class="btn btn-light" asp-action="Index">Back to List</a>
    </div>
    <hr />
    <h3>Decks<hr /></h3>
    <div class="container mt-4">
        <div class="row">
        @foreach (var item in Model.Decks)
        {
            var deck = item.Deck;
            <div class="col-md-4 col-sm-6 mb-4" onclick="ChooseGamemode(@deck.Id, @deck.Cards.Count)">
                <div class="card p-3 position-relative deck-container">
                    <div class="d-flex justify-content-between align-items-start ">
                        <div>
                            <h5 class="mb-1">@deck.Name</h5>
                            <small class="text-muted">@deck.Category.Name - @deck.Language.Name</small>
                        </div>
                        <div class="dropdown">
                            <button class="btn btn-sm btn-light dropdown-toggle" data-bs-display="static" onclick="event.stopPropagation();" type="button" id="dropdownMenuButton-@deck.Id" data-bs-toggle="dropdown" aria-expanded="false">
                                ...
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton-@deck.Id" onclick="event.stopPropagation();">
                                    <li><a class="dropdown-item" asp-controller="Decks" asp-action="Details" asp-route-id="@deck.Id">Details</a></li>
                                @if (signedIn)
                                {
                                    if (!currentUser.Saved.Any(d => d.DeckId == deck.Id))
                                    {
                                            <li><a class="dropdown-item" asp-controller="Decks" asp-action="Save" asp-route-id="@deck.Id">Save</a></li>
                                    }
                                    else
                                    {
                                            <li><a class="dropdown-item" asp-controller="Decks" asp-action="Unsave" asp-route-id="@deck.Id">Unsave</a></li>
                                    }
                                    @if (User.IsInRole("Admin") || currentUser.Id == deck.CreatorId)
                                    {
                                            <li><a class="dropdown-item" asp-controller="Decks" asp-action="Edit" asp-route-id="@deck.Id">Edit</a></li>
                                            <li><a class="dropdown-item text-danger" asp-controller="Decks" asp-action="Delete" asp-route-id="@deck.Id">Delete</a></li>
                                    }
                                    if (Model.CreatorId == currentUser.Id) {
                                            <li>
                                                <a class="dropdown-item" href="javascript:void(0);" onclick="RemoveFromCardlist(@deck.Id, @Model.Id)">
                                                    Remove from @Model.Name
                                                </a>
                                            </li>
                                    }
                                        
                                }

                            </ul>
                        </div>
                    </div>
                </div>

            </div>
        }
        </div>
    </div>
</div>

Caarta/Views/Cardlists/Edit.cshtml
@model CreateCardlistDTO

@{
    ViewData["Title"] = "Edit";
}
<div class="d-flex justify-content-center align-items-center vh-100 flex-column">

    <h3>Edit Cardlist</h3>
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-floating mb-3">

                <input asp-for="Name" class="form-control"></input>
                <label asp-for="Name" class="form-label">Name</label>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">

                <select asp-for="LanguageId" asp-items="Model.Languages" class="form-control"></select>
                <label asp-for="LanguageId" class="form-label">Language</label>
            </div>
            <div class="form-floating mb-3">

                <select asp-for="IsPublic" class="form-control">
                    <option value="true">Public</option>
                    <option value="false">Private</option>
                </select>
                <label asp-for="IsPublic" class="form-label">Visibility</label>
            </div>
            <input type="hidden" asp-for="CreatorId" />
            <input type="hidden" asp-for="TimeOfCreation" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-light" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>

    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }
</div>

Caarta/Views/Cardlists/Index.cshtml
@model IEnumerable<CardlistDTO>
@inject UserManager<AppUser> _userManager
@inject SignInManager<AppUser> SignInManager

@{
    ViewData["Title"] = "Index";
    var currentUser = await _userManager.GetUserAsync(User);
    var signedIn = SignInManager.IsSignedIn(User);
}
<div class="my-main">
    <p>
        <a class="btn btn-secondary" asp-controller="Cardlists" asp-action="Create">Add Cardlist</a>
    </p>
    <div class="container mt-4">
        <div class="row">
            @foreach (var cardlist in Model)
            {
                <div class="col-md-4 col-sm-6 mb-4" onclick="ChooseGamemode2(@cardlist.Id, @cardlist.Decks.Count)">
                    <div class="card p-3 position-relative cardlist-container">
                        <div class="d-flex justify-content-between align-items-start ">
                            <div>
                                <h5 class="mb-1">@cardlist.Name</h5>
                                <small class="text-muted">@cardlist.Language.Name</small>
                            </div>
                            <div class="dropdown">
                                <button class="btn btn-sm btn-light dropdown-toggle" data-bs-display="static" onclick="event.stopPropagation();" type="button" id="dropdownMenuButton-@cardlist.Id" data-bs-toggle="dropdown" aria-expanded="false">
                                    ...
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton-@cardlist.Id" onclick="event.stopPropagation();">
                                    <li><a class="dropdown-item" asp-action="Details" asp-route-id="@cardlist.Id">Details</a></li>
                                    @if (signedIn)
                                    {
                                        @if (User.IsInRole("Admin") || currentUser.Id == cardlist.CreatorId)
                                        {
                                            <li><a class="dropdown-item" asp-action="Edit" asp-route-id="@cardlist.Id">Edit</a></li>
                                            <li><a class="dropdown-item text-danger" asp-action="Delete" asp-route-id="@cardlist.Id">Delete</a></li>
                                        }
                                    }

                                </ul>
                            </div>
                        </div>
                    </div>

                </div>
            }
        </div>
    </div>

</div>

Caarta/Views/Cardlists/Test.cshtml
@model CardlistSimpleDTO

@{
    ViewData["Title"] = "Check Yourself";
    var cards = Model.SimpleCards;
}

<div id="cards-container" class="d-flex justify-content-center align-items-center vh-100 flex-column">
    <h4 id="cards-counter">
        1/@cards.Count
    </h4>
    <div class="d-flex justify-content-center align-items-center">
        <div class="card-container">
            <div class="card-inner">
                <div class="card-front d-flex flex-column">
                    @if (!string.IsNullOrEmpty(cards[0].FrontPictureUrl))
                    {
                        <img src="~/uploads/@cards[0].FrontPictureUrl" class="card-img" loading="lazy">
                    }
                    <div class="card-text-box">
                        <p class="card-text">@cards[0].FrontText</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="container-choices" class="d-flex justify-content-center align-items-center">
      
    </div>
    <div>
        <a class="btn btn-light" id="back-to-deck" asp-action="Details" asp-route-id="@Model.Id">Back to Deck</a>
    </div>
</div>

<script id="modelData" type="application/json">
    @Html.Raw(Json.Serialize(Model.SimpleCards))
</script>
<script src="/js/Test.js"></script>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Caarta/Views/Cardlists/TestReversed.cshtml
@model CardlistSimpleDTO

@{
    ViewData["Title"] = "Check Yourself";
    var cards = Model.SimpleCards;
}

<div id="cards-container" class="d-flex justify-content-center align-items-center vh-100 flex-column">
    <h4 id="cards-counter">
        1/@cards.Count
    </h4>
    <div class="d-flex justify-content-center align-items-center">
        <div class="card-container">
            <div class="card-inner">
                <div class="card-front d-flex flex-column">
                    @if (!string.IsNullOrEmpty(cards[0].BackPictureUrl))
                    {
                        <img src="~/uploads/@cards[0].BackPictureUrl" class="card-img" loading="lazy">
                    }
                    <div class="card-text-box">
                        <p class="card-text">@cards[0].BackText</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="container-choices" class="d-flex justify-content-center align-items-center">
    </div>
    <div>
        <a class ="btn btn-light" id="back-to-deck" asp-action="Details" asp-route-id="@Model.Id">Back to Deck</a>
    </div>
</div>

<script id="modelData" type="application/json">
    @Html.Raw(Json.Serialize(Model.SimpleCards))
</script>
<script src="/js/TestReversed.js"></script>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}